### ISSUE TITLE
What is our documentation toolchain?

### ISSUE THREAD

**Issue by dcwalk** [hyphacoop/handbook#1]
We should eventually implement a document toolchain. Some options:

- gitbook **unfortunately the `gitbook-cli` development has been discontinued**: https://github.com/GitbookIO/gitbook-cli/ 
- [Read the docs](https://github.com/rtfd/readthedocs.org) only hosted option
- [mkdocs](https://github.com/mkdocs/mkdocs/) python, mature, but the "raw" git repo is less readable than others
- [mdBook](https://rust-lang-nursery.github.io/mdBook/) rust, young (0.2.3)
- some other static site generator (e.g., Jekyll) not purpose built

**Comment by dcwalk** [comment]
In our 2019-Apr-17 all hands we discussed sharing examples of documentation here, adding in notes from that call:
- pandoc + cli
- open source blogging platform, ghost
- jekyll + travis (tag to deploy), markdown pdf [Mozilla (open) themes]
  - dependencies: https://github.com/tomeshnet/p2p-internet-workshop/blob/master/install-dependencies.sh

**Comment by benhylau** [comment]
>jekyll + travis (tag to deploy), markdown pdf [Mozilla (open) themes]

To clarify, in [tomeshnet/p2p-internet-workshop](https://github.com/tomeshnet/p2p-internet-workshop) the dependencies are used like this:

| Tool | Build | Result |
|:-----|:-----|:-------|
| jekyll | [src](https://github.com/tomeshnet/p2p-internet-workshop/tree/master/site) + [cmd](https://github.com/tomeshnet/p2p-internet-workshop/blob/v0.12/package.sh#L117) | https://tomeshnet.github.io/p2p-internet-workshop/ |
| remark | [src](https://github.com/tomeshnet/p2p-internet-workshop/blob/master/module-1/presentation.html) | https://tomeshnet.github.io/p2p-internet-workshop/articles/module-1/presentation/ |
| decktape | [src](https://github.com/tomeshnet/p2p-internet-workshop/blob/master/module-1/presentation.html) + [cmd](https://github.com/tomeshnet/p2p-internet-workshop/blob/v0.12/build.sh#L61) | https://tomeshnet.github.io/p2p-internet-workshop/articles/module-1/pdf-assets/module-1-presentation.pdf |
| markdown-pdf | [src](https://github.com/tomeshnet/p2p-internet-workshop/blob/master/module-1/README.md) + [cmd](https://github.com/tomeshnet/p2p-internet-workshop/blob/v0.12/build.sh#L24) | https://tomeshnet.github.io/p2p-internet-workshop/articles/module-1/pdf-assets/module-1.pdf |

It is quite custom and I imagine we'd only need the jekyll part if we decide to go this route at all.

**Comment by dcwalk** [comment]
Just some handbook examples:
- Root Systems (gitbook) https://www.rootsystems.nz/ --> https://github.com/root-systems/handbook
  - gitbook-cli ("legacy")
  - (hosted with gitbook for other formats): https://legacy.gitbook.com/@root-systems
  - CC BY-SA 4.0
- Scuttleverse (gitbook) https://www.scuttlebutt.nz/ --> https://github.com/ssbc/scuttlebutt.nz
  - gitbook-cli ("legacy")
- Open Data Handbook Guide (Jekyll)  http://opendatahandbook.org/guide/en/ --> https://github.com/okfn/opendatahandbook
- Mozilla Open Leader Training Series (Jekyll) https://mozilla.github.io/open-leadership-training-series/ --> https://github.com/mozilla/open-leadership-training-series (base template for p2p website)
  - jekyll
  - gh pages hosted
- IPFS Docs :page_facing_up: (hugo)  https://docs.ipfs.io/  https://github.com/ipfs/docs/
  - hugo + aegir (npm)
  - Makefile + IPFS magic :crystal_ball: https://github.com/ipfs/docs/blob/master/Makefile

**Comment by patcon** [comment]
this is good to close, right @dcwalk ?

**Comment by dcwalk** [comment]
yes, this looks good to close.
