### ISSUE TITLE
Tool: Mention service inventory?

### ISSUE THREAD

**Issue by dcwalk** [hyphacoop/handbook#12]
We should probably link to our Service Inventory, as that will be helpful for members: https://hackmd.io/WXS9Ie9wQ8OlmIhSpDpdmw?view

**Comment by patcon** [comment]
Might this fit in "Guides"? I could think of places someone might expect to see practices around it mentioned.
- **Trialling a service**
- **Discovering services we have** (clarifying that not all are official, but just have accounts accessible by members)
- **Discovering who has access to a service**

**Comment by patcon** [comment]
Or for now, we could just create a `tools.md` resource, and point to the inventory and maybe passbolt.

**Comment by patcon** [comment]
Or maybe `operations.md`?

**Comment by benhylau** [comment]
@ASoTNetworks this is what we talked about, referencing this / porting to our handbook.

**Comment by patcon** [comment]
I think it can stay where it is, no? i like how lightweight hackmd is for this, and we're in flux

This ticket was just to document how we use it, not migrate (i say as the main person maintaining it)

Created number #90, which also related to inventory

**Comment by dcwalk** [comment]
I think we just want to link to it, see my comment in #11, I was thinking more of a "quick reference" for being in our virtual office. To have one is pretty standard from any office I've ever worked in and is super helpful to know all the places to touch/review without really explaining them (just point to where they are explained)

We could have some fun with it as it is a virtual office :3

**Comment by patcon** [comment]
Talk of infra at bottom also relates to "virtual office" doc: https://github.com/hyphacoop/organizing/pull/82
