### ISSUE TITLE
Add a "Press" page

### ISSUE THREAD

**Issue by patcon** [hyphacoop/handbook#122]
(Definitely open to more _Hyphish_ name for this, rather than more recognizable "Press" page.)

In future, this might belong more on our website, or could be incorporated into a full "Press Kit", but starting small.

## Items so far

- Press
  - Canadian Worker Co-operative Federation. [Hypha Worker Co-operative Seeks to Build Bridges](https://canadianworker.coop/hypha-worker-co-operative-seeks-to-build-bridges/) (Jun 21, 2020)
  - Design Radical Futures. [Instagram post series](https://www.instagram.com/p/CNXq7w2h3Ab/)
  - ...
- Sessions, Workshops & Talks
  - (Hypha) Mozilla Festival 2021. This Is What Solidarity Looks Like — Emergent Practices from the Decentralized Co-operative Web. [details](https://schedule.mozillafestival.org/session/3BE77L-1) | [video](https://www.youtube.com/watch?v=eVLHAVg-g24#t=30m45s) (dc edit: we should say we were invited to a Panel, but COMPOST organized!)
  - (COMPOST) Dweb Meetup March 2021 — The Latest in the DWeb Ecosystem. [details](https://www.eventbrite.com/e/dweb-meetup-march-2021-the-latest-in-the-dweb-ecosystem-tickets-142013104017#) | video (pending)
  - ...
- Simple nice stuff (for low bar stuff like a wonderful tweet, etc.)
  - ...

**Comment by dcwalk** [comment]
https://www.earlymagazine.com/articles/can-a-workers-co-op-thrive-in-big-tech

**Comment by dcwalk** [comment]
https://blog.opencollective.com/emergent-practices-from-the-decentralized-co-operative-web/

**Comment by dcwalk** [comment]
https://www.youtube.com/watch?v=bp95oowQ5Hw

**Comment by dcwalk** [comment]
https://cfe.ryerson.ca/key-resources/podcasts/defund-big-tech-refund-communities
