### ISSUE TITLE
Doc: Plain-language duties and checklists for required roles: president, secretary, treasurer person

### ISSUE THREAD

**Issue by dcwalk** [hyphacoop/handbook#13]
Just drawing from the [Infrastructure and Operations working group description](https://loomio.hypha.coop/g/KvARWad7/working-groups-infrastructure-and-operations)... we committed to an initial version of the handbook having the above.

## To Do

- [x] president (@YurkoWasHere) 
- [x] secretary (@benhylau)
- [x] treasurer (???) https://github.com/hyphacoop/organizing/issues/121

**Comment by patcon** [comment]
_Ontario Co-operative Act_ says we also need an **auditor role** that one or more people hold each year (Fourth Pig called it a committee).
https://www.ontario.ca/laws/statute/90c35#BK153

**Comment by benhylau** [comment]
We should be exempt https://www.ontario.ca/laws/statute/90c35#BK152

**Comment by patcon** [comment]
Ah missed that. Thanks. Will push tracking this to finance role.

**Comment by benhylau** [comment]
Wait for bylaws draft, then can write this up

**Comment by benhylau** [comment]
Added to handbook.
