### ISSUE TITLE
Update invoice guides

### ISSUE THREAD

**Issue by dcwalk** [hyphacoop/handbook#134]
We have a bunch of places where "Transferwise" is mentioned but the URL and service name have changed: https://wise.com/gb/blog/world-meet-wise

We should update and review if this changes anything on the Beneficiary line of instructions

**Comment by benhylau** [comment]
The invoicing guides are completely outdated and I will rescope this to a full update of that section and assign to myself.

**Comment by writerly03** [comment]
Dante has updated the invoicing guide: https://github.com/hyphacoop/handbook/blob/fix/134-finance-guides/Finance/sending-invoices.md

**Comment by writerly03** [comment]
There is also this page in the handbook regarding invoices: https://handbook.hypha.coop/Finance/invoices.html

**Comment by rkashe** [comment]
@dasanchez Which is the most current information that should be in the handbook? These are the two links you shared with me this week:

Sending invoices: https://github.com/hyphacoop/handbook/blob/fix/134-finance-guides/Finance/sending-invoices.md

Paying contractors: https://github.com/hyphacoop/handbook/blob/fix/134-finance-guides/Finance/paying-invoices.md

Is there one for payroll?

Is a complete overwrite of those sections need to be done in the handbook or is just added as additional info?
