### ISSUE TITLE
Doc: What it means to be a good member

### ISSUE THREAD

**Issue by dcwalk** [hyphacoop/handbook#14]
Just drawing from the [Infrastructure and Operations working group description](https://loomio.hypha.coop/g/KvARWad7/working-groups-infrastructure-and-operations)... we committed to an initial version of the handbook having the above.

**Comment by benhylau** [comment]
Draft before AGM and discuss at AGM

**Comment by dcwalk** [comment]
Was thinking we could look at Code of Conduct models which talk about acceptable/unacceptable behaviour, and could codify our committments to equity.

Language around equity from a coc:
"providing a harassment-free, safe, and inclusive experience for everyone, regardless of personal and professional background, technical skill, gender, gender identity and expression, style of clothing, sexual orientation, dis-/ability, physical appearance, body size, race, class, age, or religion"
