### ISSUE TITLE
add ssh best practices

### ISSUE THREAD

**Issue by uditvira** [hyphacoop/handbook#147]
in chat I raised the concern that ssh-ing to our vm's over the jump server, is a multi-step error-prone process and it would be better to just get everybody using an ssh config file that deals with the proxy. @YurkoWasHere and @ASoTNetworks have some thoughts on what a useful config file can be. we should this to the handbook so we aren't all looking for it

**Comment by YurkoWasHere** [comment]
Changes made to better explain jump servers and config template for servers

https://github.com/hyphacoop/handbook/blob/master/guides.md#jump-server

Is this sufficient to close issue?
