### ISSUE TITLE
Guide: Adding new loomio groups/users

### ISSUE THREAD

**Issue by patcon** [hyphacoop/handbook#16]
🗣 **Loomio:** https://loomio.hypha.coop/d/jFvE4TIW/tool-talk-loomio

Some wierd permission stuff we should keep in mind for creating new groups:
https://matrix.to/#/!wvFLvXHaNrxWWwFOKj:tomesh.net/$1565811342176zrnUR:tomesh.net?via=tomesh.net&via=matrix.org&via=elon.li

Thinking that the doc could:
- creating a new group
  - advise adding every user to a group (they can leave if they don't want to be there) (link to [official loomio doc](https://help.loomio.org/en/user_manual/groups/membership/#managing-memberships), rather than re-explain)
  - recommend default permissive settings
  - advise promoting everyone to coordinator
- adding a new loomio user
  - add them to all groups
  - promote them to coordinator in all groups

people can leave places they don't want to be, but they should have full admin access in all spaces, right?

**Comment by patcon** [comment]
promotion to coordinator allows:
- generally managing, including moving threads, and forking comments into new threads.

**Comment by dcwalk** [comment]
We currently aren't using new groups on loomio so closing this guide for now. Can re-open if a reccomendation to use the tool emerges out of strategic planning session.
