### ISSUE TITLE
remove sunseted infra from links from handbook

### ISSUE THREAD

**Issue by dcwalk** [hyphacoop/handbook#161]
@ASoTNetworks  @YurkoWasHere documentation on current infra no longer accurate and there are some links to nowhere. Can these be updated and removed? See any of the failing PRs: #158  eg

**Comment by dcwalk** [comment]
Shouldn't Loomio still work? I thought we didn't get rid of that: https://loomio.hypha.coop

**Comment by YurkoWasHere** [comment]
There is quite allot of infra documentation changes that are needed
