### ISSUE TITLE
Payroll Task - LTD

### ISSUE THREAD

**Issue by YurkoWasHere** [hyphacoop/handbook#183]
Following needs to be added to the payroll section. 

---

Each month, access the Benefits Plan bill for the correct month for the payroll period (usually 1 month behind)
- Login to as Plan Sponsors
- Select `Account Information` (on left menu)
- Select `Bills` Tab
- Select correct month
- Select Option`Billing Statement (please remit payment based on this bill)`
- Click `View`

A PDF version of the bill will open

For each Employee calculate TLD amount by looking at value on: 
- Add the LTD values on page(s) titled "CURRENT PERIOD DETAIL LIST"  and "PRIOR PERIOD ADJUSTMENTS DETAIL LIST"
  - `Premium` Column, `Employee` Sub Column
  - `Total Amount Due for Member` row 
*Note* Adjustments are optional and there typically will not be any.

In Wage Point update the LTD deduction:
- Login to Wagepoint
- Select `Employees` tab
- Select `Edit` on the row of the employee you are updating
- Select `Deductions` tab
- Update amount per paycheck

You can click "back to list" to return to the list of employees.

**Comment by dasanchez** [comment]
Added this to https://github.com/hyphacoop/handbook/pull/226
