### ISSUE TITLE
Guide: Making decisions and configuring for private vs public sharing (various platforms)

### ISSUE THREAD

**Issue by patcon** [hyphacoop/handbook#19]
Related to #5?

Not sure what the scope of this might be, or if a guide is the best place, but soliciting feedback here.

I've been keeping a doc making it clear how to share a hackmd privately, as it's not quite intuitive:
https://hackmd.io/VN4ltoJJTwWSVdODqfBf2w

This could perhaps go in the handbook page.

We might also include:
- explanation of our Privileged vs Public GDrive areas, and what each mean/expect,
- later: explain the public vs (future) private `hyphacoop/organizing` repo for private notes,
- clarify any assumptions we have about private docs. specifically, that they will always be locked down, as people will be free to share links in public channels, under assumption that they are not publicly readable (i.e. we will never assume during creation that "this is private, so we just won't share this link, and hopefully no one will find it")
  - example: all meetings get added to link.hypha.coop/meetings, but private ones simply aren't accessible

Thinking perhaps the "philosophy" or guiding principles could go more in "Working Open", while the "how to make a private hackmd" sorta thing could go in guides?

**Comment by benhylau** [comment]
@patcon can we close this?

**Comment by patcon** [comment]
I think so. Thanks for poking it
