### ISSUE TITLE
Reorganize directory

### ISSUE THREAD

**Issue by LexaMichaelides** [hyphacoop/handbook#216]
Problem: The sidebar of the handbook has some nested sections that don't make a lot of sense. It's hard to navigate and find content at first-glance.

The Github Working Group intends to reorganize into a comprehensible nested list and combine this with folders so that everything isn't just a top-level file in the filesystem.

Google doc for working on this: https://docs.google.com/document/d/1iupcxOQLHy1nm2h1xBHbj3ExSEj0KDn1_lNTllSM5bY/edit#

- [x] Create proposed structure for table of contents
- [x] File all existing files into folders based on top-level ToC sections
- [ ] #220
- [ ] #221
- [x] Restructure SUMMARY.md to reflect all our new links and changes #217 
- [ ] #222
- [ ] #223

**Comment by LexaMichaelides** [comment]
Work begun: https://github.com/hyphacoop/handbook/tree/reorg-summary

**Comment by LexaMichaelides** [comment]
https://docs.google.com/document/d/1iupcxOQLHy1nm2h1xBHbj3ExSEj0KDn1_lNTllSM5bY/edit#

**Comment by LexaMichaelides** [comment]
Major next steps for async work:
- [ ] LEXA: Create Health and Safety page to include under Policies
- [ ] Split 'Onboarding.md' up ('Onboarding.md' should be just the onboarding checklist, a new page called 'Virtual-Office.md' should be made for everything else)
- [ ] Combing the two Initiatives.md pages in the How-We-Work folder
- [ ] Renovate the top-level pages for working groups/decide if we're keeping them (finance, infrastructure, operations)
- [ ] Ping each working group to ask them to review the pages in their section, update, or approve of removing them

**Comment by tripledoublev** [comment]
I just updated `SUMMARY.md` with the new folder structure and created a PR to merge the changes into the `reorg-summary` branch. #217

**Comment by tripledoublev** [comment]
Closing this issue as I merge #219
Outstanding tasks were made into distinct issues.
