### ISSUE TITLE
Update broken links to the handbook on the Hypha website

### ISSUE THREAD

**Issue by rkashe** [hyphacoop/handbook#234]
It looks like it is the Working Open link in the footer of each page

- https://hypha.coop/work/ -> bottom of the page, "working open"
- https://hypha.coop/people/ -> Handbook under Join the Team

**Comment by tripledoublev** [comment]
This [PR](https://github.com/hyphacoop/hypha.coop/pull/193) will fix the broken links

**Comment by rkashe** [comment]
@tripledoublev One more link to fix in this Dripline post: https://hypha.coop/dripline/how-we-co-operate/

- "We’ve even [drafted an explainer](https://handbook.hypha.coop/co-operative.html#about-us) in our handbook to clarify our own understanding! The link should be updated to this -> https://handbook.hypha.coop/Hypha-Worker-Co-operative/co-operative.html

**Comment by tripledoublev** [comment]
Created a [PR](https://github.com/hyphacoop/hypha.coop/pull/195) that fixes it

Let me know if you find any other broken link

**Comment by dasanchez** [comment]
@writerly03 can we fix the one broken link that's left and open a separate issue for backwards-compatible links?

**Comment by writerly03** [comment]
Sure, I think that's how it is set up anyway. Though looks like the PR just pushed the fix to staging not the live site. Maybe we can bundle this fix with the Distributed Press Dripline post that's supposed to go live today or tomorrow?

**Comment by dasanchez** [comment]
Broken links have been fixed.
