### ISSUE TITLE
Post re-structure links

### ISSUE THREAD

**Issue by dasanchez** [hyphacoop/handbook#238]
We should explore ideas on how to address the broken links that resulted from the big handbook re-structuring.

* Leave everything as-is
  * Broken links can be "fixed" on a case-by-case basis
* Add the old structure to redirect to the new structure ("backwards compatible" links)
  * This would result in tons of additional work to keep all pages available
* Update the 404 page to take people to handbook.hypha.coop
  * We can make this a lot more welcoming than it is now
  * https://docs.github.com/en/pages/getting-started-with-github-pages/creating-a-custom-404-page-for-your-github-pages-site

**Comment by dasanchez** [comment]
My take on this: broken links are a fact in the web. If people come to the handbook website using an old (now-broken) link and get a 404 error, they can still look for the page they're after in handbook.hypha.coop

**Comment by tripledoublev** [comment]
Thanks for opening this issue @dasanchez 

I created this [basic 404 page](https://handbook.hypha.coop/custom404) that acknowledges the broken link and automatically redirects users to the handbook's homepage.

If there is a need for edits on that page, they can be addressed in a new issue.
