### ISSUE TITLE
Refine circle ci deploy

### ISSUE THREAD

**Issue by dcwalk** [hyphacoop/handbook#26]
Deploying the handbook landed in #17 and f776d1439, but noticing some refinements need to happen:

- fix cache errors in `build-docs` workflow (aka I think this is just adding package.json) (see [recent example](https://circleci.com/gh/hyphacoop/handbook/11?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link))
- ~address something about how the gh-pages branch is both behind and ahead?~ nvm! was thinking abt this wrong
- **stretch** add new testing workflow with some sort of initial implementation of link checking or proofing?

**Comment by dcwalk** [comment]
Should we also switch to using `infra@hypha.coop` as the email address too?

**Comment by benhylau** [comment]
@ASoTNetworks ^

**Comment by dcwalk** [comment]
We already use it for website Travis notifications, see: https://github.com/hyphacoop/hypha.coop/blob/master/.travis.yml#L36

There wouldn't be any emails generated/sent by switching noreply@ to infra@ here, however it would be a real email? Not sure folks practices around this  :woman_shrugging:

**Comment by patcon** [comment]
omg, didn't realize we'd created that. (might have been me tbh)

re: email. working through it here: https://loomio.hypha.coop/d/6MDv8TWd/tool-talk-email/12

:+1: infra@hypha.coop (but maybe something else later)

Related: I've started experimenting with a spreadsheet to easily track what emails/assets we're using where, to make change processes clearer: https://docs.google.com/spreadsheets/d/1D27I7edzwpDMpw8R0XIrgz-u_O6kyCRGl8cbmG7x1IE/edit#gid=1076055360

**Comment by dcwalk** [comment]
None of this is really my area, but I was mulling on proofer options. My first thought was too use [`html-proofer`](https://github.com/gjtorikian/html-proofer) but that installed as a ruby gem usually just dropping some links for now:

- https://circleci.com/blog/automate-your-static-site-deployment-with-circleci/ 
- https://circleci.com/blog/markdown-proofer/
- https://www.abahgat.com/blog/testing-static-sites/#tweaking-the-setup

It looks like some images come with html proofer installed, e.g.: https://circleci.com/orbs/registry/orb/circleci/hugo), can we use multiple docker images and just use html-proofer from this one?! (too silly?)

On further poking:
`NOTE: For Node.js variant Docker images (tags that end in -node) the LTS release of Node.js is pre-installed.` 

So maybe we should just switch to using `circleci/ruby:2.4.2-jessie-node` and then we can install and use html-proofer?
