### ISSUE TITLE
Add guide for updating labels

### ISSUE THREAD

**Issue by patcon** [hyphacoop/handbook#39]
Re-ticketed from https://github.com/hyphacoop/organizing/issues/145#issuecomment-567426240

A place to explain what's happening, and link from the above message.

This will close out that issue.

**Comment by patcon** [comment]
First-pass text

## Managing GitHub Labels

If you'd like to **create a new label** that's sync'd across our main repos, just add it to the `hyphacoop/organizing` repo, and it will added to others.

If you'd like to **rename existing label**...

If you'd like the `hyphacoop/organizing` labels to **start sync'ing to a new repo**...

**Comment by benhylau** [comment]
@patcon can we add this to handbook and close out the task before we forget all this?

**Comment by patcon** [comment]
Closing in favour of https://github.com/hyphacoop/handbook/pull/56 and removing from board
