### ISSUE TITLE
Glossary terms

### ISSUE THREAD

**Issue by dcwalk** [hyphacoop/handbook#4]
In https://github.com/hyphacoop/handbook/pull/3/ @patcon suggested a glossary, here is a collector issue b/c I'm not sure abt rolling one now

**Comment by dcwalk** [comment]
Parallel movements:
- Platform cooperativism / co-operative https://platform.coop/ "A platform cooperative, or platform co-op, is a cooperatively owned, democratically governed business that establishes a computing platform, and uses a website, mobile app or a protocol to facilitate the sale of goods and services"
- Solidarity economy: https://ccednet-rcdec.ca/en/toolbox/building-solidarity-economy-movement-guide-grassroots "A solidarity economy is based on efforts that seek to increase the quality of life of a region or community through local business and not-for-profit endeavors."
- New economy: https://neweconomy.net/ "The “new economy” represents an emerging vision for a just, sustainable, and democratic future."
- Co-operative economy: http://www.geo.coop/about

**Comment by patcon** [comment]
- **Union.** Not sure whether glossary is place for making this distinction, but when I mention co-ops, I feel like people often confuse them for unions (or at least they'll start talking about unions), as if the same parts of their brains light up.
- [cooperative] principles. https://www.ica.coop/en/cooperatives/cooperative-identity
- our platforms. i assume we'll refer to them often in handbook, and so maybe we should have a one-liner for what each is to us? or maybe there's a better place.
  - loomio

:bulb: Keep definitions tweet-sized (old-school 140 characters) as an artificial constraint. (h/t vTaiwan)

**Comment by patcon** [comment]
Possible other terms

- billable / non-billable work
- generative / regenerative work (maybe just @benhylau's definition, but open to introducing)
- standup format
- [full] all-hands meeting
- availability calendar. calendar link
- weekly schedule. link to when2meet

**Comment by patcon** [comment]
@dcwalk mentions that glossaries are things no one ever reads. Maybe we could take a page from https://blacksocialists.us/mumbo-jumbo

they acknowledge how pretentious glossaries are, and work to make it more readable. As dc suggested, we could even call our page "Mumbo Jumbo" too

**Comment by patcon** [comment]
From convo with @benhylau [in chat](https://matrix.to/#/!wvFLvXHaNrxWWwFOKj:tomesh.net/$15662363952130QTDRz:tomesh.net), though prob better terms to find

- clip
- common pool

**Comment by patcon** [comment]
Maybe candidates: these confusing co-op / ontario ones:

(we could link out mostly. only the most high-level 140 characters or whatever)

- https://loomio.hypha.coop/d/cPnZpext/articles-of-incorporation-submission/24
  - Business Identification Number. (aka Ontario Corporation Number)
  - Business Number 
- https://loomio.hypha.coop/d/cPnZpext/articles-of-incorporation-submission/23
  - not-for-profit organization
  - not-for-profit status
  - not-for-profit co-op
  - not-for-profit corporation

**Comment by patcon** [comment]
From: https://github.com/hyphacoop/handbook/pull/31/files#r348728181

- collaborators - outside folks
- member-owners
- member-workers

**Comment by patcon** [comment]
financial terms like:

- reserves NOT profit.

**Comment by patcon** [comment]
this maybe seems like it could be elsewhere, but just because it's come up in:

- intangible personal property (IPP) > intellectual property (IP) [[1]](https://www.investopedia.com/terms/i/intangible-personal-property.asp)

**Comment by dcwalk** [comment]
@patcon reviewing a lot of these I don't think they belong in a glossary.

It seems to me glossary/whatever should be a place for commonly confused terms, or important terms that are strange to us (e.g., member-owner). As opposed to an exhaustive list of terms that we've never seen before, or that have a specific legal meaning in a specific document (e.g., object)

Also, some of these have since been linked and described elsewhere (e.g., availability calender, full all hands) so I'm hesitant to add them in an additional place

**Comment by benhylau** [comment]
I agree we should define terms as needed and with context. Terms like "clip" only makes sense within scope of finance doc and terms like IPP should not be ours to define at all.

I also feel this is not a priority task, maybe revisit around AGM?

**Comment by dcwalk** [comment]
@patcon and I have spoke recently about pushing this forward, so something will happen in the near term to set up a seed for later growth.

**Comment by dcwalk** [comment]
Closing for now because #43 landed

**Comment by patcon** [comment]
Happy to see this closed! 🎉
