### ISSUE TITLE
Does this auto-deploy?

### ISSUE THREAD

**Issue by benhylau** [hyphacoop/handbook#51]
This from a few days back is still not reflected on the website https://github.com/hyphacoop/handbook/pull/49
I just merged this hoping it would redeploy, and the GitHub Workflow failed with some weird error while building the node, and it succeeded after I re-ran it, but the website is still not updated https://github.com/hyphacoop/handbook/pull/50

<img width="914" alt="Screen Shot 2020-03-02 at 2 31 25 AM" src="https://user-images.githubusercontent.com/2261308/75638823-1479d080-5c2e-11ea-8151-4b1743234ad1.png">

Is there a manual step necessary or is something broken?

**Comment by benhylau** [comment]
Re-ran the workflow on master and finally it passed and re-deployed :) maybe it was the github outage that left this in a weird state? Feel free to close if this seems like a one off thing.

**Comment by dcwalk** [comment]
I'm going to close for now, let's re-ticket if it re-occurs?

**Comment by patcon** [comment]
admittedly `actions/setup-node@v1` is a floating reference (any v1.x.y taggs release, i believe) to a widely-used and github-maintained action.

Others had issue in last 2 days fwiw:
https://github.com/actions/setup-node/search?q=tar&type=Issues
Specific to us: https://github.com/actions/setup-node/issues/116
