### ISSUE TITLE
Automate checking and encoding of style rules

### ISSUE THREAD

**Issue by dcwalk** [hyphacoop/handbook#9]
Feedback on #3 surfaced that we have different baseline grammatical preferences and usage, in https://github.com/hyphacoop/handbook/pull/3#discussion_r282748477 @patcon  suggested:

> We could use [`vale`](https://errata-ai.github.io/vale/) and [dangerCI gem](https://danger.systems/guides/what_does_danger_do.html) to encode our rules and do some of these evolving checks. Demo: https://github.com/patcon/dangerfile-test/pull/1 (tho we'd poof a bot instead of using my github token :) )
> 
> Style rule: https://github.com/patcon/dangerfile-test/blob/master/ci/vale/styles/HyphaCoop/Eg.yml

**Comment by dcwalk** [comment]
This seems interesting to experiment with! However it also strikes me as something we can deal with down the road, rather than a pressing use case and priority

**Comment by patcon** [comment]
Another code style we could lint:
https://github.com/hyphacoop/handbook/pull/35#discussion_r349400044

**Comment by dcwalk** [comment]
Another code style also mentioned in #35 is inplementation of practice of "sentence/fragment-per-line", my comment:

```
I'm not sure how to interpret "sentence/fragment-per-line" that you all say you want as that seems to cover many cases:

- full sentence per line
- sentence fragment per line (determined not based on number of chars, assuming delimiters as break?)
- sentence fragment per line (hard rule of 80 char)
```

**Comment by benhylau** [comment]
I suggest we make one sentence per line a general practice instead of lint enforcement is a good start. 80 char per line is not useful for diffs as in the middle things get edited and that line exceeds 80 then all the lines below get overflow changed. Also adoption is hard for ppl like myself who do not already have this editor setting.
